### ISSUE TITLE
报错，The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by mymoonsoft** [alipay/agentUniverse#187]
以前不报这种错误，现在为什么会出错

**Comment by LandJerry** [comment]
> 以前不报这种错误，现在为什么会出错

读不到模型ak；看看是不是key文件没读到，或者跑的agent底层用的模型有要求

**Comment by mymoonsoft** [comment]
law_chat_bot.py  我运行这个代码就出现错误，可我已经在环境变量中配置DASHSCOPE_API_KEY

**Comment by mymoonsoft** [comment]
peer_chat_bot.py  我运行这个代码就没问题

**Comment by leonharetd** [comment]
这个问题是这样的，law_chat_bot.py 使用了两种模型导致的
law_chat_bot.yaml
```yaml
info:
  name: law_rag_agent
  description: 一个法律顾问，可以根据给出的事件，以及提供的背景知识做出客观的司法判断。
profile:
  introduction: 你是一位精通信息分析的ai法律顾问。
  target: 你的目标是根据给出的事件，以及提供的背景知识做出客观的司法判断。
  instruction: |
    你需要遵守的规则是:
    1. 必须使用中文结合背景信息做出判决，没有在背景知识中的条例不允许引用。
    2. 结构化答案生成，必要时通过空行提升阅读体验。
    3. 多考虑背景知识和场景的关联性。
    4. 多使用“根据民法典第XX条”“根据刑法第XX条”这种句式开头，但要求事件内容确实和对应条目相关，否则不要提及。
    5. 如果背景信息和内容无关则不要引用，引用条例时不要再强调“根据背景信息”这一点。


    背景信息是:
    {background}

    事件是: {input}
  llm_model:
    name: qwen_llm
    model_name: qwen-long
    temperature: 0.5
plan:
  planner:
    name: rag_planner
action:
  knowledge:
  - law_knowledge
  tool: []
metadata:
  type: AGENT
  module: sample_standard_app.app.core.agent.rag_agent_case.law_rag_agent
  class: LawRagAgent
```
这里使用了qwen-long，所以配置这个DASHSCOPE_API_KEY没问题，但是planner 中的 yaml 是这个
```yaml
info:
  name: 'rag_agent'
  description: 'rag agent'
profile:
  llm_model:
    name: 'default_openai_llm'
    model_name: 'gpt-4o'
plan:
  planner:
    name: 'rag_planner'
metadata:
  type: 'AGENT'
  module: 'agentuniverse.agent.default.rag_agent.rag_agent'
  class: 'RagAgent'
```
这里使用了 gpt-4o，所以要么你把这个也改成 qwen，要么配置 openai 的 key。
